show open ports
GitSquared/edex-ui pull request #853
Opened 2020-11-07 01:00 UTC by dimmyjr

2020-11-07 01:05 UTC, Darateja commented
Hie sir I need a job

On Sat, Nov 7, 2020, 6:31 AM Dimmy Junior <notifications@github.com> wrote:

> ------------------------------
> You can view, comment on, or merge this pull request online at:
>
>   https://github.com/GitSquared/edex-ui/pull/853
> Commit Summary
>
>    - show open ports
>
> File Changes
>
>    - *M* src/_renderer.js
>    <https://github.com/GitSquared/edex-ui/pull/853/files#diff-4216fe265d035f9f22daac4c27493244235520b219173244faf05d7bba5d92f8>
>    (3)
>    - *M* src/assets/css/extra_ratios.css
>    <https://github.com/GitSquared/edex-ui/pull/853/files#diff-9df02e15af74031521b71e67e4be6fe1d6b6cf4d0c0e584bd3b0117353a1ebe4>
>    (22)
>    - *A* src/assets/css/mod_openportlist.css
>    <https://github.com/GitSquared/edex-ui/pull/853/files#diff-6c7545764ff8104d9238bdede0eaef8552f093725ade1bd210f13d5347ac3a9b>
>    (71)
>    - *A* src/classes/openedPortList.class.js
>    <https://github.com/GitSquared/edex-ui/pull/853/files#diff-1324301df290b4c0f9ffca0418771bd171b897de38c929a2f7d930a6a60ecc1c>
>    (54)
>    - *M* src/ui.html
>    <https://github.com/GitSquared/edex-ui/pull/853/files#diff-2d3641d2bd63c2176d28594c437564b001076f3f42ceea2a4738ea15b25b8d09>
>    (2)
>
> Patch Links:
>
>    - https://github.com/GitSquared/edex-ui/pull/853.patch
>    - https://github.com/GitSquared/edex-ui/pull/853.diff
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/GitSquared/edex-ui/pull/853>, or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AQATMZV3A2TAIB5INPTIF4LSOSL5XANCNFSM4TNJY4SA>
> .
>

2020-11-07 09:26 UTC, GitSquared requested changes

2020-11-07 09:26 UTC, GitSquared commented on src/_renderer.js
> +    // window.mods.globe = new LocationGlobe("mod_column_right");
You can't deactivate existing modules, this is a merge blocker.

2020-11-07 09:26 UTC, GitSquared commented on src/_renderer.js
> +    window.mods.openportlist = new OpenPortList("mod_column_right");
Could you give me a screenshot/example of how this looks?

2020-11-14 22:34 UTC, GitSquared commented
closed as stale

2020-11-14 22:34 UTC, closed without merging

2020-11-14 23:00 UTC, dereksmartymans commented
Thanks for sending!   
  
  
  
  
  
    
  

  
  
>   
> On Nov 14, 2020 at 4:35 PM,  <Gaby (mailto:notifications@github.com)>  wrote:
>   
>   
>     
>
>
>
>   
>
> Closed  #853 (https://github.com/GitSquared/edex-ui/pull/853).
>
>   
>
> —
>  You are receiving this because you are subscribed to this thread.
>  Reply to this email directly,  view it on GitHub (https://github.com/GitSquared/edex-ui/pull/853#event-3996818716), or   unsubscribe (https://github.com/notifications/unsubscribe-auth/ARWXRV23MG24DKNARIGXXRDSP4AZXANCNFSM4TNJY4SA).
>
>   
>

2020-11-14 23:00 UTC, dereksmartymans commented
Thank you, I appreciate it.   
  
  
  
  
  
    
  

  
  
>   
> On Nov 14, 2020 at 4:35 PM,  <Gaby (mailto:notifications@github.com)>  wrote:
>   
>   
>     
>
>
>
>   
>
> closed as stale
>
>   
>
> —
>  You are receiving this because you are subscribed to this thread.
>  Reply to this email directly,   view it on GitHub (https://github.com/GitSquared/edex-ui/pull/853#issuecomment-727274685), or   unsubscribe (https://github.com/notifications/unsubscribe-auth/ARWXRV3JOMKQFDKDNLBHQYLSP4AZTANCNFSM4TNJY4SA).
>
>   
>